### ISSUE TITLE
ssse3 table size vs speed

### ISSUE THREAD

**Issue by aqrit** [lemire/simdprune#2]
a 1KB table seems faster than 1MB table for 16 MB input on my Nehalem
test [here](https://github.com/aqrit/despacer/tree/8eba15a6c5f745b6ff278387233163e4bbf77810)

Is there a special reason to pad out with last kept byte?

sorry, if I'm not benchmarking properly ...?

edit:
with a larger test the 1MB table is fastest

**Comment by lemire** [comment]
I have documented the current speed...
https://github.com/lemire/simdprune#how-fast-is-it

> a 1KB table seems faster than 1MB table
 
The 1MB table is an annoyance. I agree.

> Is there a special reason to pad out with last kept byte?

It is a useful convention. If you want to know what the last value was,  you just look at the last element of the vector. It is more useful/informative than padding with zeros, and no more expensive.

**Comment by aqrit** [comment]
the 1kb table would require extra instructions to return an intact xmm register instead of just storing the result back to memory (speed unknown)
