### ISSUE TITLE
thinprune_epi8 optimizations

### ISSUE THREAD

**Issue by animetosho** [lemire/simdprune#5]
Hi,  
I was looking at your implementations here, and thought I'd point out a few optimization opportunities I've found in the [current implementation](https://github.com/lemire/simdprune/blob/5c08b0db61ca191d7c370c419e4cc7395a783321/simdprune.h#L47) for `thinprune_epi8`:

* `mask2` should be masked with 0xFF after the shift. This allows the compiler to use `movzx` instead of a shift, whilst also protecting against a segfault in the case of bad input
* one can use `movhps` to insert the high 8 bytes directly into the high 8 bytes of the shuffle vector, rather than a shift+or
* to merge the two halves, a single shuffle with a small table can be used instead of a series of shifts and ors
* I find that for 8-bit values, a lookup table is often faster than `popcnt` (except for on recent AMD CPUs, where `popcnt` is insanely fast). In this case, if you use the optimization from the above point, the table can also be abused to pre-multiply the count, which saves a shift when calculating the address for the lookup
* suggest using aligned loads for the lookup tables. Not only are aligned loads faster (particularly on pre-Nehalem CPUs), they can sometimes be embedded into instructions without the need for a separate `movdqu` instruction. For example, your `prune_epi8` compiles to something like `vmovdqu xmm0, [rdx+rax]; vpshufb xmm0, xmm1, xmm0`, however, if you use aligned loads, it changes to `vpshufb xmm0, xmm1, [rdx+rax]`

I haven't tested for correctness, but I can't imagine that I'm far off. I came up with the following:

	static const uint8_t pshufb_combine_table[272] = {
		0x00,0x01,0x02,0x03,0x04,0x05,0x06,0x07,0x08,0x09,0x0a,0x0b,0x0c,0x0d,0x0e,0x0f,
		0x00,0x01,0x02,0x03,0x04,0x05,0x06,0x08,0x09,0x0a,0x0b,0x0c,0x0d,0x0e,0x0f,0x80,
		0x00,0x01,0x02,0x03,0x04,0x05,0x08,0x09,0x0a,0x0b,0x0c,0x0d,0x0e,0x0f,0x80,0x80,
		0x00,0x01,0x02,0x03,0x04,0x08,0x09,0x0a,0x0b,0x0c,0x0d,0x0e,0x0f,0x80,0x80,0x80,
		0x00,0x01,0x02,0x03,0x08,0x09,0x0a,0x0b,0x0c,0x0d,0x0e,0x0f,0x80,0x80,0x80,0x80,
		0x00,0x01,0x02,0x08,0x09,0x0a,0x0b,0x0c,0x0d,0x0e,0x0f,0x80,0x80,0x80,0x80,0x80,
		0x00,0x01,0x08,0x09,0x0a,0x0b,0x0c,0x0d,0x0e,0x0f,0x80,0x80,0x80,0x80,0x80,0x80,
		0x00,0x08,0x09,0x0a,0x0b,0x0c,0x0d,0x0e,0x0f,0x80,0x80,0x80,0x80,0x80,0x80,0x80,
		0x08,0x09,0x0a,0x0b,0x0c,0x0d,0x0e,0x0f,0x80,0x80,0x80,0x80,0x80,0x80,0x80,0x80,
	};
	// table modified and copied from http://graphics.stanford.edu/~seander/bithacks.html#CountBitsSetTable
	static const unsigned char BitsSetTable256mul2[256] = 
	{
	#   define B2(n) (n)*2,     (n)*2+2,     (n)*2+2,     (n)*2+4
	#   define B4(n) B2(n), B2(n+1), B2(n+1), B2(n+2)
	#   define B6(n) B4(n), B4(n+1), B4(n+1), B4(n+2)
	    B6(0), B6(1), B6(1), B6(2)
	#undef B2
	#undef B4
	#undef B6
	};
	
	// prune bytes, mask should be in [0,1<<16)
	// values corresponding to a 1-bit in the mask are removed from output
	// like thinprune_epi8 but uses a 2kB table.
	__m128i thinprune_epi8( __m128i x, int mask) {
	      int mask1 = mask & 0xFF;
	      int mask2 = (mask >> 8) & 0xFF;
	      __m128i shufmask = _mm_castps_si128(_mm_loadh_pi(
	        _mm_castsi128_ps(
	          _mm_loadl_epi64((const __m128i *)(thintable_epi8 + mask1))
	        ),
	        (const __m64 *)(thintable_epi8 + mask2)
	      ));
	      shufmask = _mm_add_epi8(shufmask, _mm_set_epi32(0x08080808, 0x08080808, 0, 0));
	      __m128i pruned = _mm_shuffle_epi8(x, shufmask);
	      intptr_t popx2 = BitsSetTable256mul2[mask1];
	      __m128i compactmask = _mm_loadu_si128((const __m128i*)(pshufb_combine_table + popx2*8));
	      return _mm_shuffle_epi8(pruned, compactmask);
	}

By my testing, with these optimizations, `thinprune_epi8` performs roughly similar to (possibly slightly faster than) `prune_epi8`, but of course, with the benefit of significantly lower cache usage.

If writing directly to memory, it may be worthwhile investigating the idea of writing the 64-bit halves directly rather than trying to compact them together.

Distantly related to #2

**Comment by lemire** [comment]
That sounds brilliant. Let us try it out!!!

**Comment by lemire** [comment]
This is superb. It is basically just as fast as `prune_epi8` and probably faster in practice.

I called in skinny prune. :-)

Merged (with credit!).

**Comment by animetosho** [comment]
Thanks for trying it out and reporting your results!

**Comment by lemire** [comment]
@animetosho I'll do more than that later. And I'll keep on crediting you.
